import { Metadata } from "next";
import React from "react";
import FormInputSignUp from "./formInput";

type Props = {};
export const metadata: Metadata = {
  title: "SignUp",
  description: "Generated by create next app",
};
const SignUpPage = (props: Props) => {
  return (
    <div className="relative w-full h-screen">
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
        <div className="border border-border p-5">
          <div className="font-semibold text-center text-2xl mb-2">SIGN UP</div>
          <div className="text-sm text-gray500">
            Enter you data to access dashboard
          </div>
          <FormInputSignUp />
        </div>
      </div>
    </div>
  );
};

export default SignUpPage;
